"""Search vocabulary for the style browser, used by build-pages-mvp.py.

QUICK_TAGS: the visual tag chips under the category filter. A style gets a tag
when any of its terms starts a word in the style's name, summary or slug.

ZH_TERMS: Chinese search words mapped to the English terms they should match.
It maps words, not styles, so new styles are covered without editing this file.
Add a line here when a Chinese query you care about returns nothing.
"""

QUICK_TAGS = [
    ("Portrait", ["portrait", "face", "close-up", "headshot"]),
    ("Manga & Comic", ["manga", "comic", "anime"]),
    ("Hand-drawn", ["doodle", "scribble", "marker", "crayon", "hand-drawn", "sketch"]),
    ("Halftone & Print", ["halftone", "riso", "xerox", "screenprint", "print"]),
    ("Retro", ["retro", "vintage", "y2k", "70s", "80s", "90s", "analog"]),
    ("Neon", ["neon", "acid", "fluorescent"]),
    ("Monochrome", ["monochrome", "black-and-white", "duotone", "noir"]),
    ("3D", ["3d", "clay", "inflat", "toy", "render"]),
    ("Mascot", ["mascot", "creature", "monster", "pet"]),
    ("Sport", ["sport", "athlete", "runner", "basketball", "football", "cycling", "racing", "motorsport", "skate", "volley"]),
    ("Food", ["food", "snack", "ramen", "coffee", "dessert", "drink", "tea", "meal"]),
    ("Fashion", ["fashion", "streetwear", "outfit", "wardrobe"]),
    ("Product", ["product", "sneaker", "footwear", "packaging", "launch"]),
]

ZH_TERMS = {
    # formats
    "海报": ["poster"],
    "封面": ["cover", "thumbnail"],
    "缩略图": ["thumbnail"],
    "广告": ["ad", "campaign"],
    "杂志": ["editorial", "magazine", "zine"],
    "编辑": ["editorial"],
    "排版": ["editorial", "layout", "type"],
    "卡片": ["card"],
    "传单": ["flyer"],
    "书封": ["book cover"],
    "包装": ["packaging"],
    "信封": ["envelope"],
    # type
    "字体": ["type", "typograph", "lettering"],
    "大字": ["megatype", "type", "headline"],
    "文字": ["type", "text", "lettering"],
    "字母": ["letter"],
    # techniques / looks
    "涂鸦": ["doodle", "scribble", "graffiti"],
    "手绘": ["hand-drawn", "doodle", "sketch", "marker"],
    "马克笔": ["marker"],
    "蜡笔": ["crayon"],
    "拼贴": ["collage", "cutout"],
    "剪贴": ["cutout", "collage"],
    "贴纸": ["sticker"],
    "网点": ["halftone"],
    "半调": ["halftone"],
    "油印": ["riso"],
    "复印": ["xerox"],
    "印刷": ["print", "riso"],
    "版画": ["engraved", "print"],
    "漫画": ["manga", "comic"],
    "动漫": ["anime", "manga"],
    "二次元": ["anime", "manga"],
    "插画": ["illustration", "vector", "doodle"],
    "矢量": ["vector"],
    "扁平": ["flat", "vector"],
    "摄影": ["photo"],
    "照片": ["photo"],
    "人像": ["portrait"],
    "肖像": ["portrait"],
    "鱼眼": ["fisheye"],
    "三维": ["3d"],
    "立体": ["3d"],
    "黏土": ["clay"],
    "玩具": ["toy"],
    "复古": ["retro", "vintage"],
    "怀旧": ["retro", "vintage", "analog"],
    "胶片": ["analog", "film"],
    "未来": ["future", "cyber"],
    "赛博": ["cyber"],
    "科技": ["tech", "hud", "cyber"],
    "霓虹": ["neon"],
    "荧光": ["neon", "acid", "fluorescent"],
    "极简": ["minimal"],
    "简约": ["minimal", "clean"],
    "黑白": ["monochrome", "black", "noir"],
    "单色": ["monochrome"],
    "双色": ["duotone"],
    "渐变": ["gradient"],
    "动感": ["kinetic", "motion", "action"],
    "速度": ["speed", "motion"],
    "街头": ["street"],
    "街拍": ["street"],
    "朋克": ["punk", "grunge"],
    "哥特": ["gothic"],
    "可爱": ["kawaii", "cute", "playful"],
    # colors
    "红色": ["red", "crimson", "scarlet"],
    "蓝色": ["blue", "cobalt"],
    "黄色": ["yellow", "lemon"],
    "绿色": ["green", "lime"],
    "橙色": ["orange", "tangerine"],
    "粉色": ["pink"],
    "紫色": ["purple", "violet"],
    # subjects
    "产品": ["product"],
    "电商": ["product", "retail", "ad"],
    "球鞋": ["sneaker", "footwear"],
    "鞋": ["footwear", "sneaker", "shoe"],
    "运动": ["sport", "athlete", "action"],
    "跑步": ["runner", "running"],
    "篮球": ["basketball"],
    "足球": ["football"],
    "赛车": ["racing", "motorsport"],
    "美食": ["food"],
    "食物": ["food"],
    "咖啡": ["coffee"],
    "饮料": ["drink"],
    "时尚": ["fashion"],
    "穿搭": ["fashion", "outfit", "streetwear"],
    "吉祥物": ["mascot"],
    "角色": ["character", "mascot"],
    "怪物": ["monster"],
    "宠物": ["pet"],
    "猫": ["cat"],
    "旅行": ["travel"],
    "旅游": ["travel"],
    "城市": ["city", "urban"],
    "地铁": ["subway", "transit"],
    "音乐": ["music"],
    "演出": ["concert", "live"],
    "品牌": ["brand", "campaign"],
    "发布": ["launch"],
    "日记": ["diary"],
    "笔记": ["notebook", "diary"],
    "韩流": ["k-pop"],
    "韩国": ["k-pop", "korean", "seoul"],
    "日本": ["tokyo", "japan"],
    "中国": ["chinese"],
    "中文": ["chinese"],
}

# Style families: variant sets of one style show as a single gallery card.
# Slugs ending in -set-NN or -part-NN join the family named by the part before
# that suffix automatically. List only exceptions here: slug -> family key.
FAMILY_OVERRIDES = {
    "monumental-sport-editorial": "monumental-editorial",
}
